<?xml version="1.0"?>
<robot name="scout" xmlns:xacro="http://www.ros.org/wiki/xacro">

   <xacro:macro name="scout" params="model mode prefix">

      <xacro:property name="M_PI" value="3.1415926535897931" />

      <xacro:include filename="$(find romea_mobile_base_description)/urdf/base4WD.chassis.xacro" />

      <xacro:property name="conf" value="$(find scout_description)/config/scout_${model}.yaml" />
      <xacro:property name="props" value="${load_yaml(conf)}" />

      <!-- Link names -->
      <xacro:property name="base_link"
         value="${props['links']['base_link_name']}" />
      <xacro:property name="base_footprint_link"
         value="${props['links']['base_footprint_link_name']}" />
      <xacro:property name="inertial_link"
         value="${props['links']['inertial_link_name']}" />
      <xacro:property name="front_left_wheel_spinning_link"
         value="${props['links']['front_left_wheel_spinning_link_name']}" />
      <xacro:property name="front_right_wheel_spinning_link"
         value="${props['links']['front_right_wheel_spinning_link_name']}" />
      <xacro:property name="rear_left_wheel_spinning_link"
         value="${props['links']['rear_left_wheel_spinning_link_name']}" />
      <xacro:property name="rear_right_wheel_spinning_link"
         value="${props['links']['rear_right_wheel_spinning_link_name']}" />

      <!-- Joint names -->
      <xacro:property name="base_footprint_joint"
         value="${props['joints']['base_footprint_joint_name']}" />
      <xacro:property name="inertial_joint"
         value="${props['joints']['inertial_joint_name']}" />
      <xacro:property name="front_left_wheel_spinning_joint"
         value="${props['joints']['front_left_wheel_spinning_joint_name']}" />
      <xacro:property name="front_right_wheel_spinning_joint"
         value="${props['joints']['front_right_wheel_spinning_joint_name']}" />
      <xacro:property name="rear_left_wheel_spinning_joint"
         value="${props['joints']['rear_left_wheel_spinning_joint_name']}" />
      <xacro:property name="rear_right_wheel_spinning_joint"
         value="${props['joints']['rear_right_wheel_spinning_joint_name']}" />

      <!-- Base Properties -->
      <xacro:property name="aabb_length"
         value="${props['geometry']['aabb']['length']}" />
      <xacro:property name="aabb_width"
         value="${props['geometry']['aabb']['width']}" />
      <xacro:property name="aabb_height"
         value="${props['geometry']['aabb']['height']}" />
      <xacro:property name="aabb_center_x"
         value="${props['geometry']['aabb']['center'][0]}" />
      <xacro:property name="aabb_center_y"
         value="${props['geometry']['aabb']['center'][1]}" />
      <xacro:property name="aabb_center_z"
         value="${props['geometry']['aabb']['center'][2]}" />

      <xacro:property name="wheelbase"
         value="${props['geometry']['axles_distance']}" />
      <xacro:property name="front_track"
         value="${props['geometry']['front_axle']['wheels_distance']}" />
      <xacro:property name="rear_track"
         value="${props['geometry']['rear_axle']['wheels_distance']}" />
      <xacro:property name="track"
         value="${front_track}" />

      <xacro:property name="ground_clearance"
         value="${chassis_props['ground_clearance']}" />

      <xacro:property name="mass_body"
         value="${props['inertia']['mass']}" />
      <xacro:property name="mass_base"
         value="${props['inertia']['mass']}" />
      <xacro:property name="mass_center_x"
         value="${props['inertia']['center'][0]}" />
      <xacro:property name="mass_center_y"
         value="${props['inertia']['center'][1]}" />
      <xacro:property name="mass_center_z"
         value="${props['inertia']['center'][2]}" />

      <xacro:property name="ground_clearance"
         value="${props['geometry']['ground_clearance']}" />
      <xacro:property name="body_reference_x"
         value="${props['control_point'][0]}" />


      <!-- Steering Properties -->
      <xacro:property name="front_wheel_y_offset"
         value="${props['geometry']['front_axle']['wheels']['hub_carrier_offset']}" />
      <xacro:property name="rear_wheel_y_offset"
         value="${props['geometry']['rear_axle']['wheels']['hub_carrier_offset']}" />
      <xacro:property name="wheel_y_offset"
         value="${front_wheel_y_offset}" />

      <!-- Wheel Properties -->
      <xacro:property name="front_hub_carrier_offset"
         value="${props['geometry']['front_axle']['wheels']['hub_carrier_offset']}" />
      <xacro:property name="rear_hub_carrier_offset"
         value="${props['geometry']['rear_axle']['wheels']['hub_carrier_offset']}" />
      <xacro:property name="front_wheel_radius"
         value="${props['geometry']['front_axle']['wheels']['radius']}" />
      <xacro:property name="rear_wheel_radius"
         value="${props['geometry']['rear_axle']['wheels']['radius']}" />
      <xacro:property name="front_wheel_width"
         value="${props['geometry']['front_axle']['wheels']['width']}" />
      <xacro:property name="rear_wheel_width"
         value="${props['geometry']['rear_axle']['wheels']['width']}" />

      <xacro:property name="maximal_wheel_speed"
         value="${props['wheels_speed_control']['command']['maximal_speed']}" />

      <xacro:property name="wheel_mass" value="5" />
      <xacro:property name="front_wheel_mass" value="5" />
      <xacro:property name="rear_wheel_mass" value="5" />
      <xacro:property name="chassis_height"
         value="${min(front_wheel_radius,rear_wheel_radius)}" />

      <xacro:chassis>
         <!-- visual chassis -->
         <xacro:if value="${model == 'mini'}">
            <visual>
               <origin
                  xyz="${aabb_center_x-body_reference_x+0.02} ${aabb_center_y-0.015}  ${aabb_center_z-chassis_height-0.08}"
                  rpy="0 0 ${-M_PI/2.}" />
               <geometry>
                  <mesh filename="package://scout_description/meshes/scout_mini_chassis.STL" />
               </geometry>
            </visual>
         </xacro:if>
         <xacro:if value="${model == 'v2'}">
            <visual>
               <origin
                  xyz="${aabb_center_x-body_reference_x} ${aabb_center_y}  ${aabb_center_z-chassis_height}"
                  rpy="0 0 0" />
               <geometry>
                  <mesh filename="package://scout_description/meshes/scout_v2_chassis.dae" />
               </geometry>
            </visual>
         </xacro:if>
         <!-- <visual>
            <origin
               xyz="${aabb_center_x-body_reference_x} ${aabb_center_y}  ${aabb_center_z-chassis_height}"
               rpy="0 0 0" />
            <geometry>
               <box size="${aabb_length} ${aabb_width} ${aabb_height}" />
            </geometry>
         </visual> -->
         <!-- visual front wheel -->
         <cylinder length="${front_wheel_width}" radius="${front_wheel_radius}" />
         <!-- visual rear wheel -->
         <cylinder length="${rear_wheel_width}" radius="${rear_wheel_radius}" />
      </xacro:chassis>

   </xacro:macro>

</robot>