<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:macro name="chassis_visual">
        <xacro:if value="${model == 'mini'}">
            <visual>
                <origin
                    xyz="${aabb_center_x-body_reference_x+0.02} ${aabb_center_y-0.015}  ${aabb_center_z-chassis_height-0.08}"
                    rpy="0 0 ${-M_PI/2.}" />
                <geometry>
                    <mesh filename="package://scout_description/meshes/scout_mini_chassis.STL" />
                </geometry>
            </visual>
        </xacro:if>
        <xacro:if value="${model == 'v2'}">
            <visual>
                <origin
                    xyz="${aabb_center_x-body_reference_x} ${aabb_center_y}  ${aabb_center_z-chassis_height}"
                    rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://scout_description/meshes/scout_v2_chassis.dae" />
                </geometry>
            </visual>
        </xacro:if>
    </xacro:macro>


</robot>