/**:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mobile_base_controller:
      type: romea_mobile_base_controllers/MobileBaseController4WD
