type: 4WD
geometry:
  axles_distance: 0.452
  front_axle:
    wheels_distance: 0.490
    wheels:
      radius: 0.0875
      width: 0.08
      hub_carrier_offset: 0.0
  rear_axle:
    wheels_distance: 0.490
    wheels:
      radius: 0.0875
      width: 0.08
      hub_carrier_offset: 0.0
  aabb:
    length: 0.500
    width: 0.320
    height: 0.245
    center: [0., 0., 0.245]
  ground_clearance: 0.115

wheels_speed_control:
  command:
    maximal_speed: 3.0
    maximal_acceleration: 1.0
  sensor:
    speed_std: 0.1
    speed_range: 3.0

inertia:
  mass: 22.5
  center: [0., 0., 0.245]
  z_moment: 10.0 # To be configured

control_point: [0.0, 0.0, 0.0]

joints:
  base_footprint_joint_name: base_footprint
  inertial_joint_name: inertial_joint
  front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
  front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
  rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
  rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

links:
  base_link_name: base_link
  base_footprint_link_name: base_footprint
  inertial_link_name: inertial_link
  front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
  front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
  rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
  rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link
