type: 4WD
geometry:
  axles_distance: 0.498
  front_axle:
    wheels_distance: 0.583
    wheels:
      radius: 0.165
      width: 0.116
      hub_carrier_offset: 0.0
  rear_axle:
    wheels_distance: 0.583
    wheels:
      radius: 0.165
      width: 0.116
      hub_carrier_offset: 0.0
  aabb:
    length: 0.930
    width: 0.40000
    height: 0.207
    center: [0., 0., 0.245]
  ground_clearance: 0.135

wheels_speed_control:
  command:
    maximal_speed: 1.5
    maximal_acceleration: 1.0
  sensor:
    speed_std: 0.1
    speed_range: 1.5

inertia:
  mass: 68.
  center: [0., 0., 0.245]
  z_moment: 10.0 # To be configured

control_point: [0.0, 0.0, 0.0]

joints:
  base_footprint_joint_name: base_footprint
  inertial_joint_name: inertial_joint
  front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
  front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
  rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
  rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

links:
  base_link_name: base_link
  base_footprint_link_name: base_footprint
  inertial_link_name: inertial_link
  front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
  front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
  rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
  rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link
